### ISSUE TITLE
Overriding Injection Tokens not working for createComponentFactory

### ISSUE THREAD

**Issue by Kurtz1993** [ngneat/spectator#337]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I am trying to override a provider's value that's tied to an InjectionToken with no luck.

This is my createComponentFactory function where I'm setting up the providers.
![image](https://user-images.githubusercontent.com/5412470/90542115-3f5ad100-e149-11ea-973d-3b35b8300a8f.png)

Here, in my test where I'm trying to override that same provider.
![image](https://user-images.githubusercontent.com/5412470/90542152-4c77c000-e149-11ea-9f50-a420a3e68b1d.png)

This is the result. Nothing had changed.
![image](https://user-images.githubusercontent.com/5412470/90542182-55689180-e149-11ea-972d-f117e3255a2d.png)

## Expected behavior
The provider should be overriden.

## Environment

<pre><code>
Angular version: 10.0.8

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.20.1
- Platform:  Windows 10

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Please provide a reproduction example.

**Comment by Kurtz1993** [comment]
@NetanelBasal here's a quick example of that.

https://github.com/Kurtz1993/spectator-issue

**Comment by adrianrutkowski** [comment]
@Kurtz1993 in this test case

`it('should get the mocked instance of STATE injection token', () => { ... })`

you are trying to recreate component when TestBed is already initialized under the hood by

`beforeEach(() => {
    spectator = createComponent();
  });`

It's an inconsistency on the Angular side, because it throws error when using override... methods after TestBest initialization, but not in overrideProvider case. I have created pull request which should fix this issue in Angular repository https://github.com/angular/angular/pull/38717

**Comment by bboydflo** [comment]
I have updated to angular 11 where the issue is fixed (now throwing an error if attempting to ovveride providers) and I think that makes spectator code to fail. I think the issue is here: https://github.com/ngneat/spectator/blob/master/projects/spectator/src/lib/spectator/create-factory.ts#L96 so I assume spectator does not officially support angular 11?

**Comment by stefanoww** [comment]
I might take that one if it's still open.

**Comment by NetanelBasal** [comment]
@stefanoww you can take it.

**Comment by nikulin-anton** [comment]
The problem is still relevant. Now I am creating a new `createComponentFactory` in each `describe` with different providers. Please fix it.
